// src/games/quizblitz/questions.js

// Question bank
export const questionBank = {
    "Trivia": [
      { question: "What is the capital of France?", choices: ["Paris", "London", "Berlin", "Madrid"], answer: 0 },
      { question: "Who wrote 'Hamlet'?", choices: ["Shakespeare", "Dickens", "Hemingway", "Orwell"], answer: 0 },
      { question: "What is the largest planet in our Solar System?", choices: ["Mars", "Earth", "Jupiter", "Saturn"], answer: 2 },
      { question: "Which element has the chemical symbol 'O'?", choices: ["Osmium", "Oxygen", "Hydrogen", "Gold"], answer: 1 },
      { question: "In which year did World War II end?", choices: ["1963", "1945", "1939", "1918"], answer: 1 },
      { question: "Who painted the Mona Lisa?", choices: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Van Gogh"], answer: 2 },
      { question: "Which ocean is the largest?", choices: ["Atlantic", "Indian", "Pacific", "Arctic"], answer: 2 },
      { question: "What is the tallest mountain in the world?", choices: ["K2", "Mount Everest", "Kangchenjunga", "Lhotse"], answer: 1 },
      { question: "Who is known as the 'Father of Computers'?", choices: ["Alan Turing", "Steve Jobs", "Charles Babbage", "Bill Gates"], answer: 2 },
      { question: "Which country is known as the Land of the Rising Sun?", choices: ["Thailand", "China", "South Korea", "Japan"], answer: 3 },
      { question: "How many continents are there?", choices: ["5", "6", "7", "8"], answer: 2 },
      { question: "Which gas do plants absorb from the atmosphere?", choices: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen"], answer: 0 },
      { question: "Who discovered penicillin?", choices: ["Louis Pasteur", "Marie Curie", "Alexander Fleming", "Gregor Mendel"], answer: 2 },
      { question: "What is the largest mammal?", choices: ["Giraffe", "Blue Whale", "Elephant", "Hippopotamus"], answer: 1 },
      { question: "What is the smallest prime number?", choices: ["1", "2", "3", "0"], answer: 1 },
      { question: "Which planet is known as the Red Planet?", choices: ["Mercury", "Venus", "Mars", "Jupiter"], answer: 2 },
      { question: "What is the square root of 144?", choices: ["12", "14", "16", "10"], answer: 0 },
      { question: "Which language has the most native speakers?", choices: ["English", "Spanish", "Hindi", "Mandarin Chinese"], answer: 3 },
      { question: "Who was the first President of the United States?", choices: ["Thomas Jefferson", "George Washington", "Abraham Lincoln", "John Adams"], answer: 1 },
      { question: "Which planet has rings?", choices: ["Earth", "Saturn", "Mars", "Venus"], answer: 1 },
      { question: "What is H2O commonly known as?", choices: ["Water", "Oxygen", "Hydrogen", "Salt"], answer: 0 },
      { question: "Which country hosted the 2016 Summer Olympics?", choices: ["China", "USA", "UK", "Brazil"], answer: 3 },
      { question: "Which organ pumps blood through the body?", choices: ["Heart", "Lungs", "Liver", "Kidneys"], answer: 0 },
      { question: "Who invented the telephone?", choices: ["Nikola Tesla", "Thomas Edison", "Alexander Graham Bell", "Guglielmo Marconi"], answer: 2 },
      { question: "Which planet is closest to the Sun?", choices: ["Mercury", "Venus", "Earth", "Mars"], answer: 0 },
      { question: "What is the main ingredient in sushi?", choices: ["Rice", "Fish", "Seaweed", "Egg"], answer: 0 },
      { question: "Which is the fastest land animal?", choices: ["Lion", "Tiger", "Cheetah", "Leopard"], answer: 2 },
      { question: "What is the hardest natural substance?", choices: ["Gold", "Diamond", "Iron", "Quartz"], answer: 1 },
      { question: "Which continent is Egypt in?", choices: ["Europe", "Asia", "Africa", "South America"], answer: 2 },
      { question: "What is the chemical symbol for gold?", choices: ["Au", "Ag", "Gd", "Go"], answer: 0 },
      { question: "How many planets are in our solar system?", choices: ["8", "9", "7", "10"], answer: 0 },
      { question: "Which is the largest country by area?", choices: ["Canada", "Russia", "China", "USA"], answer: 1 },
      { question: "Which organ is responsible for breathing?", choices: ["Lungs", "Heart", "Stomach", "Kidneys"], answer: 0 },
      { question: "Who wrote '1984'?", choices: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "J.K. Rowling"], answer: 0 },
      { question: "What is the currency of Japan?", choices: ["Dollar", "Yen", "Euro", "Peso"], answer: 1 },
      { question: "Which is the largest desert in the world?", choices: ["Gobi", "Sahara", "Kalahari", "Arabian"], answer: 1 },
      { question: "Who painted the Starry Night?", choices: ["Claude Monet", "Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso"], answer: 2 },
      { question: "Which element has atomic number 1?", choices: ["Helium", "Hydrogen", "Oxygen", "Carbon"], answer: 1 },
      { question: "Which country is famous for the Eiffel Tower?", choices: ["France", "Italy", "Germany", "Spain"], answer: 0 },
      { question: "How many bones are in the adult human body?", choices: ["210", "206", "208", "201"], answer: 1 },
      { question: "What is the freezing point of water?", choices: ["100°C", "0°C", "32°C", "-1°C"], answer: 1 },
      { question: "Which planet is known as the Morning Star?", choices: ["Venus", "Mars", "Jupiter", "Mercury"], answer: 0 },
      { question: "Who discovered gravity?", choices: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla"], answer: 0 },
      { question: "Which is the largest mammal on land?", choices: ["Elephant", "Hippopotamus", "Giraffe", "Rhino"], answer: 0 },
      { question: "What is the main language spoken in Brazil?", choices: ["Portuguese", "Spanish", "English", "French"], answer: 0 },
      { question: "Which city is the capital of Australia?", choices: ["Sydney", "Canberra", "Melbourne", "Perth"], answer: 1 },
      { question: "What is the fastest bird?", choices: ["Ostrich", "Peregrine Falcon", "Eagle", "Hawk"], answer: 1 },
      { question: "Which metal is liquid at room temperature?", choices: ["Mercury", "Iron", "Gold", "Silver"], answer: 0 },
      { question: "Which is the smallest country in the world?", choices: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], answer: 1 },
      { question: "Who wrote 'Pride and Prejudice'?", choices: ["Charlotte Bronte", "Mary Shelley", "Jane Austen", "Emily Bronte"], answer: 2 },
      { question: "Which is the largest ocean?", choices: ["Atlantic", "Pacific", "Indian", "Arctic"], answer: 1 },
      { question: "Which gas do humans breathe in?", choices: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"], answer: 0 },
      { question: "Which is the longest river in the world?", choices: ["Yangtze", "Nile", "Amazon", "Mississippi"], answer: 1 },
      { question: "What is the hottest planet in the solar system?", choices: ["Venus", "Mercury", "Mars", "Jupiter"], answer: 0 },
      { question: "Which is the most spoken language worldwide?", choices: ["Mandarin Chinese", "English", "Hindi", "Spanish"], answer: 0 }
    ],

    "Idioms": [
      { question: "What does 'Break the ice' mean?", choices: ["Start a conversation", "Shatter glass", "Cool down", "Relax"], answer: 0 },
      { question: "What does 'Hit the sack' mean?", choices: ["Go to sleep", "Punch someone", "Start work", "Play a game"], answer: 0 },
      { question: "What does 'Let the cat out of the bag' mean?", choices: ["Reveal a secret", "Release a cat", "Make a mistake", "Hide something"], answer: 0 },
      { question: "What does 'Piece of cake' mean?", choices: ["Something easy", "Dessert", "A small problem", "A reward"], answer: 0 },
      { question: "What does 'Under the weather' mean?", choices: ["Feeling sick", "Outside", "Sunny day", "Rainy day"], answer: 0 },
      { question: "What does 'Cost an arm and a leg' mean?", choices: ["Very expensive", "Physically hurt", "Cheap", "Painful"], answer: 0 },
      { question: "What does 'Bite the bullet' mean?", choices: ["Face a difficult situation", "Chew something", "Run away", "Scream"], answer: 0 },
      { question: "What does 'The ball is in your court' mean?", choices: ["It's your decision", "Play tennis", "Throw a ball", "Take action"], answer: 0 },
      { question: "What does 'Burn the midnight oil' mean?", choices: ["Work late at night", "Use a candle", "Sleep early", "Study in the morning"], answer: 0 },
      { question: "What does 'Hit the nail on the head' mean?", choices: ["Be exactly right", "Build something", "Make a mistake", "Ignore"], answer: 0 },
      { question: "What does 'Kick the bucket' mean?", choices: ["Die", "Play football", "Escape", "Hit something"], answer: 0 },
      { question: "What does 'Let sleeping dogs lie' mean?", choices: ["Avoid trouble", "Wake the dog", "Go for a walk", "Ignore"], answer: 0 },
      { question: "What does 'Once in a blue moon' mean?", choices: ["Rarely", "Always", "Sometimes", "Never"], answer: 0 },
      { question: "What does 'Speak of the devil' mean?", choices: ["Talking about someone who appears", "Scaring someone", "Discuss evil", "Gossip"], answer: 0 },
      { question: "What does 'See eye to eye' mean?", choices: ["Agree", "Look carefully", "Disagree", "Ignore"], answer: 0 },
      { question: "What does 'Cry over spilled milk' mean?", choices: ["Regret something that can't be changed", "Spill milk", "Be sad for no reason", "Clean a mess"], answer: 0 },
      { question: "What does 'Hit the books' mean?", choices: ["Study hard", "Throw books", "Read lightly", "Ignore studies"], answer: 0 },
      { question: "What does 'Barking up the wrong tree' mean?", choices: ["Make a wrong assumption", "Yell loudly", "Walk in the forest", "Find something"], answer: 0 },
      { question: "What does 'Pull someone's leg' mean?", choices: ["Tease someone", "Help someone", "Kick someone", "Lie"], answer: 0 },
      { question: "What does 'Raining cats and dogs' mean?", choices: ["Heavy rain", "Animals falling", "Sunny weather", "Stormy night"], answer: 0 },
      { question: "What does 'Cut corners' mean?", choices: ["Do something quickly and badly", "Take shortcuts", "Use scissors", "Save money"], answer: 0 },
      { question: "What does 'Add fuel to the fire' mean?", choices: ["Make a situation worse", "Cook faster", "Fight", "Clean"], answer: 0 },
      { question: "What does 'Back to square one' mean?", choices: ["Start over", "Go back", "Lose a game", "Repeat"], answer: 0 },
      { question: "What does 'Hit the jackpot' mean?", choices: ["Win big", "Lose", "Play casino", "Succeed slightly"], answer: 0 },
      { question: "What does 'Throw in the towel' mean?", choices: ["Give up", "Fight", "Wash", "Cheer"], answer: 0 },
      { question: "What does 'Jump on the bandwagon' mean?", choices: ["Follow a trend", "Dance", "Ride a vehicle", "Join a game"], answer: 0 },
      { question: "What does 'Keep your chin up' mean?", choices: ["Stay positive", "Lift something", "Smile", "Ignore"], answer: 0 },
      { question: "What does 'Hit below the belt' mean?", choices: ["Do something unfair", "Punch", "Lie", "Cheat"], answer: 0 },
      { question: "What does 'Bite off more than you can chew' mean?", choices: ["Take on too much", "Eat quickly", "Talk too much", "Ignore"], answer: 0 },
      { question: "What does 'Face the music' mean?", choices: ["Accept the consequences", "Sing", "Run", "Hide"], answer: 0 },
      { question: "What does 'Throw caution to the wind' mean?", choices: ["Take risks", "Be careful", "Play safe", "Relax"], answer: 0 },
      { question: "What does 'Under your nose' mean?", choices: ["Right in front of you", "Hidden", "Far away", "Secret"], answer: 0 },
      { question: "What does 'By the skin of your teeth' mean?", choices: ["Narrowly succeed", "Fail", "Cheat", "Win easily"], answer: 0 },
      { question: "What does 'Burn bridges' mean?", choices: ["Destroy relationships", "Build bridges", "Ignore", "Fix"], answer: 0 },
      { question: "What does 'Cry wolf' mean?", choices: ["Raise a false alarm", "Be sad", "Lie to parents", "Alert"], answer: 0 },
      { question: "What does 'Elephant in the room' mean?", choices: ["Obvious problem", "Big elephant", "Ignore", "Hidden issue"], answer: 0 },
      { question: "What does 'Hit the roof' mean?", choices: ["Become very angry", "Climb", "Fall", "Shout"], answer: 0 },
      { question: "What does 'In hot water' mean?", choices: ["In trouble", "Boiling water", "Angry", "Sad"], answer: 0 },
      { question: "What does 'Kick the habit' mean?", choices: ["Stop a bad habit", "Dance", "Kick", "Sleep"], answer: 0 },
      { question: "What does 'Let sleeping dogs lie' mean?", choices: ["Avoid trouble", "Wake the dog", "Fight", "Ignore"], answer: 0 },
      { question: "What does 'Pull yourself together' mean?", choices: ["Calm down", "Cry", "Shout", "Run"], answer: 0 },
      { question: "What does 'Steal someone's thunder' mean?", choices: ["Take credit for someone else", "Sing loudly", "Shout", "Ignore"], answer: 0 },
      { question: "What does 'Take it with a grain of salt' mean?", choices: ["Don't take it too seriously", "Believe everything", "Eat salt", "Ignore"], answer: 0 },
      { question: "What does 'The early bird catches the worm' mean?", choices: ["Be punctual", "Sleep late", "Be lazy", "Ignore"], answer: 0 },
      { question: "What does 'Through thick and thin' mean?", choices: ["Stay loyal", "Leave", "Argue", "Ignore"], answer: 0 },
      { question: "What does 'When pigs fly' mean?", choices: ["Something impossible", "Flying pigs", "Rare event", "Never"], answer: 0 },
      { question: "What does 'Your guess is as good as mine' mean?", choices: ["I don’t know", "You know better", "Guess", "Think"], answer: 0 }
    ],
  
"Critical Thinking": [
  { question: "If all roses are flowers and some flowers fade quickly, which is true?", choices: ["Some roses fade quickly", "All flowers are roses", "All roses fade quickly", "None fade"], answer: 0 },
  { question: "You see a car moving at a constant speed. Which force is acting on it?", choices: ["Gravity", "Friction", "Balanced forces", "Acceleration"], answer: 2 },
  { question: "All cats are mammals. Whiskers is a cat. Therefore, Whiskers is?", choices: ["A reptile", "A mammal", "An amphibian", "A bird"], answer: 1 },
  { question: "If a train leaves at 10am and arrives at 2pm, the total travel time is?", choices: ["2 hours", "4 hours", "6 hours", "8 hours"], answer: 1 },
  { question: "Which is the logical conclusion? If it rains, the ground gets wet.", choices: ["Ground gets wet only at night", "If ground is wet, it rained", "Rain causes wet ground", "Wet ground causes rain"], answer: 2 },
  { question: "A store sells 5 apples for $10. How much for 8 apples?", choices: ["$14", "$16", "$18", "$20"], answer: 1 },
  { question: "If some birds can fly and a penguin is a bird, can it fly?", choices: ["Yes", "No", "Maybe", "Cannot tell"], answer: 1 },
  { question: "Which statement is a valid inference? All humans are mortal. Socrates is human.", choices: ["Socrates is immortal", "Socrates is mortal", "All humans are Socrates", "Cannot infer"], answer: 1 },
  { question: "A box contains 3 red and 2 blue balls. Probability of picking a red ball?", choices: ["1/5", "2/5", "3/5", "4/5"], answer: 2 },
  { question: "If a=b and b=c, then a=? ", choices: ["b", "c", "a=c", "a≠c"], answer: 2 },
  { question: "Which pattern comes next: 2, 4, 8, 16, ?", choices: ["20", "32", "24", "40"], answer: 1 },
  { question: "All squares are rectangles. Some rectangles are not squares. Is every square a rectangle?", choices: ["Yes", "No", "Cannot tell", "Sometimes"], answer: 0 },
  { question: "If the first two statements are true, is the final statement true? All fish live in water. Salmon is a fish. Salmon lives in water.", choices: ["True", "False", "Cannot tell", "Maybe"], answer: 0 },
  { question: "Which number is the odd one out: 2, 3, 5, 9?", choices: ["2", "3", "5", "9"], answer: 3 },
  { question: "If the code for CAT is DBU, then DOG is?", choices: ["EPH", "DNG", "EOG", "EPG"], answer: 0 },
  { question: "If A>B and B>C, then which is correct?", choices: ["A>C", "C>A", "B>A", "B<C"], answer: 0 },
  { question: "Which is not a logical statement?", choices: ["All birds can fly", "Some dogs can swim", "Blue is faster than red", "Water is wet"], answer: 2 },
  { question: "If two pencils cost $1.50, how much for 10 pencils?", choices: ["$5", "$7.50", "$6", "$8"], answer: 1 },
  { question: "You have a sequence: 1, 1, 2, 3, 5, ?, what comes next?", choices: ["5", "8", "7", "10"], answer: 1 },
  { question: "If all squares are shapes and all shapes have sides, do squares have sides?", choices: ["Yes", "No", "Cannot tell", "Sometimes"], answer: 0 },
  { question: "Which is a contradiction? ", choices: ["All humans are mortal", "I am a square circle", "Birds have wings", "Fish swim"], answer: 1 },
  { question: "If today is Monday, what day is 3 days later?", choices: ["Tuesday", "Wednesday", "Thursday", "Friday"], answer: 2 },
  { question: "If some cars are red and some are blue, which is true?", choices: ["All cars are red", "All cars are blue", "Some cars are red or blue", "No cars are red"], answer: 2 },
  { question: "Which is a valid analogy? Dog: Puppy :: Cat: ?", choices: ["Kitten", "Lion", "Tiger", "Cub"], answer: 0 },
  { question: "If 5x = 20, then x = ?", choices: ["2", "3", "4", "5"], answer: 2 },
  { question: "All roses are flowers. Some flowers fade fast. Which statement is correct?", choices: ["Some roses fade fast", "All roses fade fast", "No roses fade", "Cannot tell"], answer: 0 },
  { question: "If a train travels 60 km/h for 2 hours, distance covered?", choices: ["100 km", "120 km", "80 km", "140 km"], answer: 1 },
  { question: "If it takes 3 painters 4 hours to paint a wall, how long for 6 painters?", choices: ["2 hours", "3 hours", "4 hours", "1 hour"], answer: 0 },
  { question: "Which is a correct inference? If it snows, it is cold. It is snowing.", choices: ["It is warm", "It is cold", "Cannot tell", "It is raining"], answer: 1 },
  { question: "If the pattern is 5, 10, 15, ?, what comes next?", choices: ["20", "25", "30", "35"], answer: 1 },
  { question: "Which is the odd one out? Apple, Banana, Carrot, Grape", choices: ["Apple", "Banana", "Carrot", "Grape"], answer: 2 },
  { question: "If 2 pencils cost $3, 5 pencils cost?", choices: ["$5", "$6", "$7.50", "$8"], answer: 2 },
  { question: "If a>b>c, which is correct?", choices: ["a>c", "c>a", "b>c", "a<b"], answer: 0 },
  { question: "Which of the following is a paradox?", choices: ["This sentence is false", "I like pizza", "Sun rises in east", "Water is wet"], answer: 0 },
  { question: "If today is Friday, 2 days ago was?", choices: ["Wednesday", "Thursday", "Tuesday", "Monday"], answer: 1 },
  { question: "If x+y=10 and y=4, x=?", choices: ["6", "4", "10", "14"], answer: 0 },
  { question: "All squares are shapes. All shapes have sides. Therefore, squares have?", choices: ["Corners", "Sides", "Edges", "Vertices"], answer: 1 },
  { question: "Which is an illogical statement?", choices: ["Water is wet", "Fire is cold", "Sun is hot", "Ice is cold"], answer: 1 },
  { question: "If 3x+2=11, x=?", choices: ["3", "2", "4", "5"], answer: 0 },
  { question: "Which number is missing: 2, 4, 6, ?, 10", choices: ["7", "8", "9", "6"], answer: 1 },
  { question: "If all birds have wings and a penguin is a bird, can it fly?", choices: ["Yes", "No", "Sometimes", "Cannot tell"], answer: 1 },
  { question: "If today is Monday, 10 days later is?", choices: ["Wednesday", "Thursday", "Friday", "Saturday"], answer: 3 },
  { question: "A cube has how many faces?", choices: ["4", "6", "8", "12"], answer: 1 },
  { question: "If some A are B, some B are C, can we say some A are C?", choices: ["Yes", "No", "Cannot tell", "Maybe"], answer: 2 },
  { question: "If 7x = 49, x=?", choices: ["5", "6", "7", "8"], answer: 2 },
  { question: "Which pattern continues: 1, 4, 9, 16, ?", choices: ["20", "25", "30", "36"], answer: 1 },
  { question: "Which is not a logical deduction?", choices: ["All humans are mortal", "Socrates is human", "Socrates is mortal", "Socrates is immortal"], answer: 3 },
  { question: "If two angles of a triangle are 60° and 70°, the third is?", choices: ["50°", "60°", "70°", "90°"], answer: 0 },
  { question: "If a car travels 100 km in 2 hours, its speed is?", choices: ["40 km/h", "50 km/h", "60 km/h", "70 km/h"], answer: 2 },
  { question: "Which of these is a logical conclusion? If it rains, the ground is wet. The ground is wet.", choices: ["It rained", "It did not rain", "Cannot tell", "Always wet"], answer: 2 },
  { question: "Which is a logical inference? All men are mortal. Socrates is a man.", choices: ["Socrates is mortal", "Socrates is immortal", "Cannot tell", "Maybe"], answer: 0 }
],
"General Knowledge": [
    { question: "Which planet is known as the Red Planet?", choices: ["Mars", "Venus", "Jupiter", "Saturn"], answer: 0 },
    { question: "What is the largest ocean on Earth?", choices: ["Atlantic", "Indian", "Pacific", "Arctic"], answer: 2 },
    { question: "Who painted the Mona Lisa?", choices: ["Van Gogh", "Leonardo da Vinci", "Michelangelo", "Raphael"], answer: 1 },
    { question: "Which country is known as the Land of the Rising Sun?", choices: ["China", "Japan", "Thailand", "South Korea"], answer: 1 },
    { question: "What is the capital of Australia?", choices: ["Sydney", "Canberra", "Melbourne", "Perth"], answer: 1 },
    { question: "Which gas do humans breathe in?", choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"], answer: 0 },
    { question: "Who wrote '1984'?", choices: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "J.K. Rowling"], answer: 0 },
    { question: "Which is the smallest country in the world?", choices: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], answer: 1 },
    { question: "How many continents are there?", choices: ["5", "6", "7", "8"], answer: 2 },
    { question: "Which organ pumps blood through the body?", choices: ["Heart", "Lungs", "Liver", "Kidneys"], answer: 0 },
    { question: "Who invented the telephone?", choices: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"], answer: 1 },
    { question: "Which planet has rings?", choices: ["Saturn", "Mars", "Earth", "Venus"], answer: 0 },
    { question: "What is the main ingredient in sushi?", choices: ["Rice", "Fish", "Seaweed", "Egg"], answer: 0 },
    { question: "Which is the fastest land animal?", choices: ["Cheetah", "Lion", "Tiger", "Leopard"], answer: 0 },
    { question: "What is the chemical symbol for gold?", choices: ["Au", "Ag", "Fe", "Pb"], answer: 0 },
    { question: "Which country hosted the 2016 Summer Olympics?", choices: ["Brazil", "China", "USA", "UK"], answer: 0 },
    { question: "Which is the largest desert in the world?", choices: ["Sahara", "Gobi", "Kalahari", "Arabian"], answer: 0 },
    { question: "Who painted the Starry Night?", choices: ["Vincent van Gogh", "Claude Monet", "Pablo Picasso", "Leonardo da Vinci"], answer: 0 },
    { question: "Which element has atomic number 1?", choices: ["Hydrogen", "Helium", "Oxygen", "Carbon"], answer: 0 },
    { question: "Which city is the capital of France?", choices: ["London", "Paris", "Berlin", "Rome"], answer: 1 },
    { question: "What is the freezing point of water?", choices: ["0°C", "32°C", "-1°C", "100°C"], answer: 0 },
    { question: "Who discovered gravity?", choices: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla"], answer: 0 },
    { question: "Which is the largest mammal on land?", choices: ["Elephant", "Hippopotamus", "Giraffe", "Rhino"], answer: 0 },
    { question: "What is the main language spoken in Brazil?", choices: ["Portuguese", "Spanish", "English", "French"], answer: 0 },
    { question: "What is the currency of Japan?", choices: ["Yen", "Dollar", "Euro", "Peso"], answer: 0 },
    { question: "Which is the most spoken language worldwide?", choices: ["Mandarin Chinese", "English", "Spanish", "Hindi"], answer: 0 },
    { question: "Which planet is closest to the Sun?", choices: ["Mercury", "Venus", "Earth", "Mars"], answer: 0 },
    { question: "How many bones are in the adult human body?", choices: ["206", "210", "208", "201"], answer: 0 },
    { question: "Which is the hottest planet in the solar system?", choices: ["Venus", "Mercury", "Mars", "Jupiter"], answer: 0 },
    { question: "Which city is the capital of the USA?", choices: ["New York", "Washington D.C.", "Los Angeles", "Chicago"], answer: 1 },
    { question: "Which organ is responsible for breathing?", choices: ["Lungs", "Heart", "Stomach", "Kidneys"], answer: 0 },
    { question: "Which is the longest river in the world?", choices: ["Nile", "Amazon", "Yangtze", "Mississippi"], answer: 0 },
    { question: "What is H2O commonly known as?", choices: ["Water", "Hydrogen", "Oxygen", "Salt"], answer: 0 },
    { question: "Which metal is liquid at room temperature?", choices: ["Mercury", "Iron", "Gold", "Silver"], answer: 0 },
    { question: "Which continent is Egypt in?", choices: ["Africa", "Europe", "Asia", "South America"], answer: 0 },
    { question: "Which is the largest country by area?", choices: ["Russia", "Canada", "China", "USA"], answer: 0 },
    { question: "Which language has the most native speakers?", choices: ["Mandarin Chinese", "English", "Spanish", "Hindi"], answer: 0 },
    { question: "Who was the first President of the United States?", choices: ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"], answer: 0 },
    { question: "Which is the fastest bird?", choices: ["Peregrine Falcon", "Ostrich", "Eagle", "Hawk"], answer: 0 },
    { question: "Which city is known as the Big Apple?", choices: ["Los Angeles", "New York", "Chicago", "Miami"], answer: 1 },
    { question: "Which is the tallest mountain in the world?", choices: ["Mount Everest", "K2", "Kangchenjunga", "Lhotse"], answer: 0 },
    { question: "Which country is famous for the Eiffel Tower?", choices: ["Italy", "France", "Germany", "Spain"], answer: 1 },
    { question: "Which is the largest desert in Africa?", choices: ["Kalahari", "Sahara", "Namib", "Gobi"], answer: 1 },
    { question: "Which gas do plants absorb from the atmosphere?", choices: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen"], answer: 0 },
    { question: "Which country hosted the 2012 Summer Olympics?", choices: ["China", "UK", "Brazil", "USA"], answer: 1 },
    { question: "Which is the currency of the UK?", choices: ["Dollar", "Euro", "Pound Sterling", "Yen"], answer: 2 },
    { question: "Which animal is known as the King of the Jungle?", choices: ["Tiger", "Lion", "Elephant", "Leopard"], answer: 1 },
    { question: "Which continent is the largest by area?", choices: ["Asia", "Africa", "Europe", "North America"], answer: 0 },
    { question: "Which organ detoxifies the body?", choices: ["Kidney", "Liver", "Heart", "Lungs"], answer: 1 },
    { question: "Which planet is the largest in the solar system?", choices: ["Jupiter", "Saturn", "Earth", "Neptune"], answer: 0 },
    { question: "Which is the capital city of Canada?", choices: ["Toronto", "Vancouver", "Ottawa", "Montreal"], answer: 2 }
  ]  
  };
  
  // ✅ Function to shuffle choices randomly
  export function shuffleQuestionChoices(questions) {
    return questions.map((q) => {
      const correctAnswer = q.choices[q.answer];
      const shuffledChoices = [...q.choices].sort(() => Math.random() - 0.5);
      const newAnswerIndex = shuffledChoices.indexOf(correctAnswer);
      return { ...q, choices: shuffledChoices, answer: newAnswerIndex };
    });
  }
  